version: '3.8'

services:
  # MySQL Database Service
  webphim-mysql:
    image: mysql:8.0
    container_name: webphim-mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3307}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME:-webphim}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis Cache Service
  webphim-redis:
    image: redis:7.2-alpine
    container_name: webphim-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-dxh1234}

volumes:
  mysql_data:
  redis_data:
